updated micro-rdk-modular-driver-examples
viam-labs/micro-rdk-modular-driver-examples pull request #6
Opened 2024-06-04 18:10 UTC by allisonschiang

-updated example so it can compile

2024-06-04 19:59 UTC, mattjperez requested changes
Looking great! 
let's remove all the commented out code first

2024-06-04 19:59 UTC, mattjperez commented on src/moisture_sensor.rs
> +//pub struct MoistureSensor{reader : dyn AnalogReader<u16,Error = SensorType>}
rm since it's been replaced fully

2024-06-04 19:59 UTC, mattjperez commented on src/moisture_sensor.rs
> +
nit: rm this extra newline

2024-06-04 19:59 UTC, mattjperez commented on src/moisture_sensor.rs
> +        // Ok(Arc::new(Mutex::new(Self {reader})))
remove this since you reimplemented it

2024-06-04 20:25 UTC, acmorrow requested changes

2024-06-04 20:25 UTC, acmorrow commented on Cargo.toml
> +micro-rdk = {git = "https://github.com/viamrobotics/micro-rdk.git", version = "0.1.9-rc2", rev = "3aae9aa"}
rc3 is out

2024-06-04 20:25 UTC, acmorrow commented on src/moisture_sensor.rs
> +pub fn register_model(registry: &mut ComponentRegistry) -> Result<(), RegistryError> {
In the other review, I believe you renamed this from `register_model` to `register_models`: https://github.com/viam-labs/micro-rdk-esp32-sensor-examples/pull/6/files#diff-a019dea011c6ec55007918304246cb63a3292f4670e1ef259bf65c6cd6a48672R23 for the per-type registration. Let's do it here too then.

2024-06-04 20:25 UTC, acmorrow commented on src/moisture_sensor.rs
> +#[derive(DoCommand)]
Please add a blank line after the `}` before starting a new thing.

2024-06-04 20:25 UTC, acmorrow commented on src/water_pump.rs
> +pub fn register_model(registry: &mut ComponentRegistry) -> Result<(), RegistryError> {
Ditto `model` vs `models`.

2024-06-04 20:25 UTC, acmorrow commented on src/water_pump.rs
> +    pub fn from_config(cfg: ConfigType, deps: Vec<Dependency>) -> Result<MotorType, crate::water_pump::MotorError> {
Why does `crate::water_pump::MotorError` need the explicit namespacing?

2024-06-07 17:24 UTC, acmorrow approved these changes
LGTM

2024-06-07 19:08 UTC, merged